<a href="https://colab.research.google.com/github/apconrado/Projeto-Teste-Publico/blob/master/C%C3%B3pia_de_Numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Começaremos a manipular nesse momento os elementos constituintes da biblioteca Numpy.

In [ ]:
import numpy as np

In [ ]:
obj = np.array([10, 20, 30, 40, 50, 60, 70, 80])
print(obj)

[10 20 30 40 50 60 70 80]


In [ ]:
type(obj)

numpy.ndarray

O objeto array, compartilha das mesmas propriedades que vimos anteriormente nas listas:

1. indexação
2. Subset por indexação
3. Filtros

In [ ]:
obj[0]

10

In [ ]:
##Primeiros 3 elementos de um array

obj[:3]

array([10, 20, 30])

In [ ]:
obj[-3:]

array([60, 70, 80])

In [ ]:
##Todos os elementos do Array podem ser expressos por meio de um vetor de elementos verdadeiros ou falsos

obj > 30

## cada elemento no array que for menor que 30, retornará como falso, se não, retorna como verdadeiro

array([False, False, False,  True,  True,  True,  True,  True])

Podemos usar essa estrutura para realizar o nosso primeiro filtro usando Numpy:

In [ ]:
obj[obj > 30]

##esse elemento obj quando combinado com [] (colchetes), e dentro do colchete retornar o objeto original, acrescentado de um operador lógico > (maior) e um valor (30), 
##retorna uma versão baseada no filtro que vimos no caso anterior.
##Com isso, temos o nosso array sem os elementos que são false no caso anterior.

array([40, 50, 60, 70, 80])

Assim como no caso das listas, array também tem a propriedade de mutabilidade, basta acessar o índice e com isso, alterar o valor do objeto array.

In [ ]:
obj[0] = 50
obj

##veja que o elemento 0, que anteriormente valia 10, agora vale 50.

array([50, 20, 30, 40, 50, 60, 70, 80])

Diferente das listas, arrays não operam apenas em uma única dimensão, vamos trabalhar com uma matriz quadrada 3x3:

Devemos prestar atenção aqui (muita atenção), porque um array de dimensão superior é declarado primeiro com um colchete para todos os arrays [], e depois cada array é declarado de forma independente separado por vígula.

O que diferencia aqui um array de uma dimensão para um 2darray, é que temos dentro do colchete, uma nova variável. [linhas, colunas]

In [ ]:
obj2 = np.array([[1,2,3],[4,5,6],[7,8,9]])
obj2

array([[1, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

In [ ]:
obj2[0,0]

1

Perceba aqui, que para 'acessar' o valor do objeto de duas dimensões, precisamos exatamente de duas instruções. Simples assim.

In [ ]:
obj2[0, 0] = 3
obj2

array([[3, 2, 3],
       [4, 5, 6],
       [7, 8, 9]])

Podemos seccionar um array2d usando dois operadores se subset:

In [ ]:
##Pegamos os dois elementos das linhas e colunas
obj2[:2, :2]

array([[3, 2],
       [4, 5]])